### ISSUE TITLE
LibreCAD does not open, only shows splash screen

### ISSUE THREAD

**Issue by ksio89** [LibreCAD/LibreCAD#1880]
### Expected behavior
application opens

### Observed behavior
I'm experiencing the same issues as #1817 on all 2.2.1 release candidate and 2.2.2 alpha builds: the Loading... splash screen is shown but the application does not open. Uninstalling and reinstalling the same or newer builds does not fix it. 

The only workaround I've found is uninstall LC, install **2.2.0.2-14-g10ad9444** and then reinstall newer builds, but eventually it will stop launching again.

### Steps to reproduce or sample file
start the application

### Operating System and LibreCAD version info
OS: Windows 11 Home 23H2
LibreCAD version: 2.2.1_rc3-20-gd7446c30-win64

**Comment by app4soft** [comment]
> OS: Windows 11

Might be issue of LibreCAD's Windows builds or Windows-specific issue.

On Linux all works.

**Comment by dxli** [comment]
@ksio89 


Could you run from  cmd and with the option -d6 ?

Please upload the console output here.

I cannot reproduce this issue here.

**Comment by ksio89** [comment]
I fixed the issue by uninstalling LibreCAD and then cleaning all remaining data and registry entries with Revo Uninstaller. It was some configuration created on 2.2.0 that was conflicting with 2.2.1 release candidate and 2.2.2 alpha builds. 

I'll keep using 2.2.1 rc and and backup LC folder on AppData, I just hope it won't happen again when it gets a final release.

**Comment by dxli** [comment]
Let's make this one as a blocker for the 2.2.1 release.

We process the following at startup:

Command alias；
Block Library;
Fonts;
General preferences for the app (not for drawings).

Let's review each, and at least generate informative error messages upon crashes.

**Comment by Questions2000** [comment]
@ksio89 
Not sure if this is helpful / the same issue you are experiencing but also take a look at this #1809 post.
Not sure if you edit your librecad.alias file to setup custom hotkeys?  but it could have been what your Revo Uninstaller took care of.  It might have deleted your older librecad.alias which maybe was the cause?
There appeared to be a bug regarding the librecad.alias file with newer releases.
Hopefully this is helpful, if not I apologize if this has nothing to do with your issue.

**Comment by dxli** [comment]
Alias crash should have been fixed, 2.2.1 or 2.2.2

If you have an alias file causing the crash, please share.

**Comment by ksio89** [comment]
> @ksio89 Not sure if this is helpful / the same issue you are experiencing but also take a look at this #1809 post. (I had made a link for this in my 1817 post, just mentioning just in case it was not seen) Not sure if you edit your librecad.alias file to setup custom hotkeys? but it could have been what your Revo Uninstaller took care of. It might have deleted your older librecad.alias which maybe was the cause? There appeared to be a bug regarding the librecad.alias file with newer releases that has now been corrected. (Using Linux so not sure if Windows version experienced the same issue)
> 
> Hopefully this is helpful, if not I apologize if this has nothing to do with your issue.

I also suspected that it was a custom libreacad.alias that was preventing LC from opening, but the crash persisted even with default alias file.

**Comment by dxli** [comment]
I still couldn't reproduce this issue 

I have added extra logging for alias handling.

Please install the latest 2.2.2-alpha build and run it in cmd with the command line parameter "-d6", and upload the output( as much as available).

**Comment by ksio89** [comment]
@dxli The parameter ``-d6`` doesn't seem to do anything, as nothing is output to the console.

**Comment by app4soft** [comment]
> The parameter -d6 doesn't seem to do anything, as nothing is output to the console.

@ksio89 You should add "space" before number: `-d 6`

**Comment by ksio89** [comment]
> > The parameter -d6 doesn't seem to do anything, as nothing is output to the console.
> 
> @ksio89 You should add "space" before number: `-d 6`

Still nothing, and I tested on an elevated prompt as well.

**Comment by lordofbikes** [comment]
There is no console output on Windows. This only works on Linux or MacOS.

**Comment by dxli** [comment]
@ksio89 

I have enabled console debug info for windows for 2.2.2-alpha.

Could you try the latest build in cmd with "librecad.exe -d6"?

**Comment by ksio89** [comment]
Here it is @dxli:

[Administrador Prompt de comando - LibreCAD.exe  -d 6.txt](https://github.com/user-attachments/files/16966668/Administrador.Prompt.de.comando.-.LibreCAD.exe.-d.6.txt)

**Comment by dxli** [comment]
@ksio89 

Thanks for the crashing logs.

It confirms the crash is not due to alias or block Library handling.

The trouble is we still don't have the exact cause of the crash.

**Comment by ksio89** [comment]
@dxli I'm confused because it's not actually crashing anymore after fully uninstalling 2.2.0 before upgrading to either 2.2.1 rc or 2.2.2 alpha. If you wish, I can try to reproduce the issue in a virtual machine, by installing 2.2.0 and then 2.2.1 or 2.2.2 builds.

**Comment by dxli** [comment]
That's a great point.

After this fix, we would add a way for auto crash reporting like crash pad in 2.2.2

**Comment by ksio89** [comment]
@dxli The crash has reappeared on 2.2.1 rc, so I updated to 2.2.2 alpha to generate a log:

[LibreCAD log.txt](https://github.com/user-attachments/files/17006609/LibreCAD.log.txt)

**Comment by dxli** [comment]
Thanks a lot!

This appears to be the menu entry for recent files, which need a code review.

Hopefully, this will be the last blocker for the official 2.2.1 release

**Comment by ksio89** [comment]
You're right about the crash being caused by recent files, because deleting all entries on key _`[HKEY_CURRENT_USER\Software\LibreCAD\LibreCAD\RecentFiles]`_ fixes it. Not ideal, but at least I know there's a workaround. On the positive side, I finally found that LC settings are stored on Registry, so I backed up LibreCAD key before uninstalling it.

**Comment by dxli** [comment]
@sand1024 
I am reviewing and rewriting some really old code here in 2.2.1.

I feel we need to rewrite in 2.2.2 also.
