### ISSUE TITLE
Pasted polygons end up as line segments instead of polyline

### ISSUE THREAD

**Issue by Questions2000** [LibreCAD/LibreCAD#2379]
### Expected Behavior
When copy and paste polygons to have them remain as a polyline.

### Observed Behavior
If you cut or copy a polygon and then paste it, the polygon pastes as line segments instead of being a polyline.

### Steps To Reproduce
-Open empty drawing
-Draw rectangle
-Select rectangle (notice that the rectangle is all one piece)
-Hit CTRL+X to cut retangle or CTRL+C to copy rectangle
-Select insertion point
-Hit CTRL+V to paste rectangle
-Click anywhere in drawing pane where you want to paste the rectangle
-Then on rectangle, you will notice the rectangle is now 4 line segments instead of 1 connected polyline

### Operating System and LibreCAD Version
LibreCAD-2.2.2_alpha1-501-g79fa989d0.AppImage
Version: 2.2.2.5-alpha
Compiler: GNU GCC 13.3.0
Compiled on: Nov 23 2025
Qt Version: 6.4.2
Boost Version: 1.83.0
System: Debian GNU/Linux 12 (Bookworm) (X11)

**Comment by sand1024** [comment]
@Questions2000 
Yes, thank you for reporting this. 
It was introduced in one of latest build.   
I suppose this is applicable not only for polygons, but for other entities that may be expanded. 

@dxli
Locally I've fixed this and will commit as part of a larger PR

**Comment by Questions2000** [comment]
Tested this in the following version and this still appears to occur
`LibreCAD-2.2.2_alpha1-513-ga52767402.AppImage`
not sure if fix was applied?

**Comment by sand1024** [comment]
@Questions2000 
well, it's fixed in my local sources, yet no, this change is not in master yet and so is not available in release versions. It will be part of larger PR from me.
